"""Render the event store to Markdown views. The JSONL files are the source of truth;
these files are regenerated after every write and must not be edited by hand."""

from __future__ import annotations

from pathlib import Path

from .store import Board, BoardError

BANNER = "<!-- GENERATED by baton from {src}. Do not edit; use the `baton` CLI. -->"


def header(t: dict) -> str:
    return f"### [{t['id']}] {t['from']} → {', '.join(t['to'])} · status: {t['status']} · {t['ts']}"


def one_line(t: dict) -> str:
    title = t["title"] or first_line(t["body"])
    return f"[{t['id']}] {t['from']} → {', '.join(t['to'])} · {t['status']} · {t['ts']} · {title}"


def first_line(body: str, width: int = 100) -> str:
    line = next((ln.strip() for ln in body.splitlines() if ln.strip()), "")
    line = line.replace("**", "")
    return line if len(line) <= width else line[: width - 1] + "…"


def entry_md(t: dict) -> str:
    out = [header(t)]
    if t["title"]:
        out.append(f"**{t['title']}**")
    meta = []
    if t.get("files"):
        meta.append("Files: " + ", ".join(f"`{f}`" for f in t["files"]))
    if t.get("cites"):
        meta.append("Cites: " + ", ".join(t["cites"]))
    if t.get("blocks"):
        meta.append("Blocks: " + ", ".join(t["blocks"]))
    if meta:
        out.append(" · ".join(meta))
    if t["body"]:
        out.append(t["body"])
    for r in t["replies"]:
        lines = r["body"].splitlines() or [""]
        out.append(f"> [A] {r['from']} · {r['ts']}: {lines[0]}")
        out.extend(f">   {ln}" for ln in lines[1:])
    if t["status"] == "CLOSED" and t.get("closed_by"):
        reason = f" — {t['closed_reason']}" if t.get("closed_reason") else ""
        out.append(f"> status: CLOSED by {t['closed_by']}{reason}")
    return "\n".join(out) + "\n"


def board_md(board: Board, sprint: str, live: bool) -> str:
    threads = [t for t in board.entries().values() if t["sprint"] == sprint]
    src = f"{board.cfg['dir']}/{sprint}.jsonl"
    title = "Coordination board" if live else "Coordination board archive"
    out = [BANNER.format(src=src), "", f"# {title}: {sprint}", ""]
    if live:
        out += [
            ("> Append-only. Post with `baton post`, answer with `baton reply`, close with "
             "`baton close`. Find any entry from any sprint with `baton show <ID>`."),
            "",
        ]
        carried = [t for t in board.open_threads() if t["sprint"] != sprint]
        if carried:
            out += ["## Still open from earlier sprints", ""]
            out += [f"- {one_line(t)} ({t['sprint']})" for t in carried]
            out += [""]
    out += [entry_md(t) for t in threads]
    return "\n".join(out).rstrip() + "\n"


def status_md(board: Board) -> str:
    rows = board.status()
    out = [BANNER.format(src=f"{board.cfg['dir']}/status.json"), "", "# Status", "",
           "| Role | Phase | State | Last hand-off | Updated |", "|---|---|---|---|---|"]
    for role in sorted(rows):
        r = rows[role]
        state = r["state"].replace("|", "\\|").replace("\n", " ")
        out.append(f"| {role} | {r['phase']} | {state} | {r['handoff']} | {r['updated']} |")
    return "\n".join(out) + "\n"


def contracts_md(board: Board) -> str:
    out = [BANNER.format(src=board.cfg["dir"]), "", "# Contracts index (C- entries)", "",
           "> Read a contract with `baton show <ID>`.", "",
           "| ID | owner → audience | defines | files | sprint | status |", "|---|---|---|---|---|---|"]
    for t in board.entries().values():
        if t["kind"] != "C":
            continue
        title = (t["title"] or first_line(t["body"], 80)).replace("|", "\\|")
        files = "; ".join(t.get("files", [])) or "—"
        out.append(f"| {t['id']} | {t['from']} → {', '.join(t['to'])} | {title} | {files} "
                   f"| {t['sprint']} | {t['status']} |")
    return "\n".join(out) + "\n"


def is_generated(path: Path) -> bool:
    if not path.exists():
        return True
    with path.open() as f:
        return f.readline().startswith("<!-- GENERATED by baton")


def write(path: Path, text: str) -> None:
    """Write a generated view. Never overwrites a file baton did not generate."""
    if not is_generated(path):
        raise BoardError(f"{path} was not generated by baton; import it (`baton import`) "
                         f"and move it aside before rendering over it")
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text)
    tmp.replace(path)


def render_all(board: Board) -> list[Path]:
    """Regenerate the live board, the status table and the contracts index."""
    cfg, root = board.cfg, board.root
    written = []
    for key, text in (
        ("board_md", board_md(board, cfg["sprint"], live=True)),
        ("status_md", status_md(board)),
        ("contracts_index", contracts_md(board)),
    ):
        if cfg.get(key):
            write(root / cfg[key], text)
            written.append(root / cfg[key])
    return written


def render_archive(board: Board, sprint: str) -> Path:
    path = board.root / board.cfg["archive_dir"] / f"BOARD-{sprint}.md"
    write(path, board_md(board, sprint, live=False))
    return path
